### ISSUE TITLE
is compatible with r2dbc?

### ISSUE THREAD

**Issue by solinad21** [knowm/Yank#117]
I want to start a project with spring boot and I can only select r2dbc drivers (mysql/mariadb), 

are they compatible with yank?

![yank-test](https://user-images.githubusercontent.com/1120174/169705734-4d73bd97-e964-4daa-92c7-2206e359c934.JPG)

**Comment by timmolter** [comment]
I'm pretty sure it's not compatible, since I developed it originally for JDBC.
