### ISSUE TITLE
Update dependency dbutils to 1.8

### ISSUE THREAD

**Issue by deenar** [knowm/Yank#64]
Dbutils 1.7 isn't thread safe. https://issues.apache.org/jira/browse/DBUTILS-135. A fix is available in DbUtils 1.8 (due to be released shortly).

**Comment by timmolter** [comment]
Thanks. I'll keep an eye out for it. Feel free to post a message here when it's available.

**Comment by deenar** [comment]
Tim 

Will do. 

For those who want to use yank in a multi-threaded fashion, you can downgrade the dbutils dependency to 1.6. It is compatible .
   <dependency>
      <groupId>org.knowm</groupId>
      <artifactId>yank</artifactId>
      <version>3.3.3</version>
      <exclusions>
        <exclusion>
          <groupId>commons-dbutils</groupId>
          <artifactId>commons-dbutils</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>commons-dbutils</groupId>
      <artifactId>commons-dbutils</artifactId>
      <version>1.6</version>
    </dependency>

**Comment by deenar** [comment]
For those who want to use Yank in a multi-threaded scenario one can downgrade dbutils to 1.6, see below. it is binary compatible.
>    <dependency>

      <groupId>org.knowm</groupId>
      <artifactId>yank</artifactId>
      <version>3.3.3</version>
      <exclusions>
        <exclusion>
          <groupId>commons-dbutils</groupId>
          <artifactId>commons-dbutils</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>commons-dbutils</groupId>
      <artifactId>commons-dbutils</artifactId>
      <version>1.6</version>
    </dependency>
